### ISSUE TITLE
Finish fishing progression tree

### ISSUE THREAD

**Issue by braulio-dev** [Mykindos/BetterPvP#109]
- [ ] Fishing Frenzy event where everybody gets weight and catch rate increase. Maybe shop sell prices are multiplied
- [x] Add more perks

Perks done:
- [x] Base fishing (Clans Only)
- [x] Drop Multiplier
- [x] Swimmer re-roll chance to Treasure
- [x] Fish weight multiplier
- [x] Fish duplicator

**Comment by Mykindos** [comment]
A scaling passive between say 0->250 that has a chance to double the fish you receive

A scaling passive , 250-500 that has a chance to increase weight of fish you catch

500 -> alongside base fishing, baits last twice as long or something

750-1000 increased legendary chance or somethin

**Comment by StudentAlleg** [comment]
Currently working on chance for additional dropd

**Comment by StudentAlleg** [comment]
Bait length done, but relies on #124

**Comment by StudentAlleg** [comment]
Currently working on refactoring so that perks can be added that allow for modifying weight of fish/chance.
