### ISSUE TITLE
Fishing rods cause velocity to players and entities

### ISSUE THREAD

**Issue by StudentAlleg** [Mykindos/BetterPvP#1146]

**Comment by Mykindos** [comment]
Needs some clarification, they are meant to pull players which is also considered velocity

**Comment by StudentAlleg** [comment]
> Needs some clarification, they are meant to pull players which is also considered velocity

Ok I guess the players is intended, though I disagree with that. Entities would be things like mythic mobs

**Comment by StudentAlleg** [comment]
intended
