### ISSUE TITLE
Update storm sphere description

### ISSUE THREAD

**Issue by 8SIXSect** [Mykindos/BetterPvP#1158]
- Storm Sphere strikes its targets with Lightning but this isn't told to the user
- This Lightning Strike adds additional damage to the ability and should be disclosed.

**Comment by StudentAlleg** [comment]
Lighting does not appear to be doing any damage, it should just be the regular damage of the bow. Just tested this, and saw no damage from lighting. (If you hold a book, it will tell you the damage causes and the amount)
