### ISSUE TITLE
Force users to use full set.

### ISSUE THREAD

**Issue by StudentAlleg** [Mykindos/BetterPvP#123]
On equip of an armour piece, all other pieces are automatically equipped if they exist, otherwise the original armour piece is rejected. Force players to be either be in kit or not.

**Comment by braulio-dev** [comment]
Why

**Comment by StudentAlleg** [comment]
> Why

qol/prevent confusion with mixed sets. Probably have a switch cooldown.

**Comment by StudentAlleg** [comment]
Incompatible with embuements
