### ISSUE TITLE
You can use longshot in an allies claim

### ISSUE THREAD

**Issue by StudentAlleg** [Mykindos/BetterPvP#1268]

**Comment by StudentAlleg** [comment]
Code says it should not

**Comment by Mykindos** [comment]
Is there evidence of this actually happening? It doesn't tell the player outside of particles if its working or not

**Comment by StudentAlleg** [comment]
> Is there evidence of this actually happening? It doesn't tell the player outside of particles if its working or not

Tankless said that it was, but I don't think there is any proof
