### ISSUE TITLE
Flash stops regenerating charges if an Assassin relogs

### ISSUE THREAD

**Issue by Mykindos** [Mykindos/BetterPvP#134]
Use charges and then relog
You will have no charges and they will no longer generate

**Comment by ezrn** [comment]
The way to fix this is probobly by force re-equipping the armor set when players log back in. Since they will be loading the texture pack during this time, it won't affect much.

**Comment by Mykindos** [comment]
> The way to fix this is probobly by force re-equipping the armor set when players log back in. Since they will be loading the texture pack during this time, it won't affect much.

that has to be the worst fix possible, it aint that complicated

**Comment by ezrn** [comment]
> > The way to fix this is probobly by force re-equipping the armor set when players log back in. Since they will be loading the texture pack during this time, it won't affect much.
> 
> that has to be the worst fix possible, it aint that complicated

I mean you'd just have to de-equip their boots and re-requip them it's not very complicated. This would also display their skills every time they log in so they could remember what they were running. Could probably find a better fix inside the Flash class itself though.
