### ISSUE TITLE
Riposte overrides title of other cooldown despite not having a title

### ISSUE THREAD

**Issue by StudentAlleg** [Mykindos/BetterPvP#138]
@ezrn: theres some weird cooldown display shenanigans going on here https://discord.com/channels/161738857136521217/1154342231721910302/1164795317296828426

**Comment by ezrn** [comment]
pretty sure this has nothing to do with riposte

**Comment by braulio-dev** [comment]
The expected behavior of action bar cooldowns for skills is for them to only display whilst you're holding a weapon that can cast the skill. In this case, you'll only get the action bar cooldown for bulls charge for as long as you're holding your axe. Is there something I'm not seeing?
