### ISSUE TITLE
Add enable/disable to all features

### ISSUE THREAD

**Issue by StudentAlleg** [Mykindos/BetterPvP#140]
This already exists for skills, expand to all features to allow for quick killswitching.

Features that require this:
**Clans**

- [x] Insurance
- [x] Pillage
- [x] Dominance

**Core**

- [x] Tips

**Progression**

- [x] Fishing Tree
- [x] Mining Tree
- [x] Fishing bait
- [x] Fishing Loot

**Comment by Mykindos** [comment]
Do you have a list of features that doesn't have it, I think most do

**Comment by StudentAlleg** [comment]
No, I know a lot do have it. Specifically know that progression perks do not currently.

**Comment by Mykindos** [comment]
@braulio-dev 😠

**Comment by StudentAlleg** [comment]
I'll put going through everything and making sure it exists on my to-do list

**Comment by braulio-dev** [comment]
Do you mean just a switch for individual perks?

**Comment by StudentAlleg** [comment]
Yes for perks, I don't know if it exists for trees. This should be something I am capable of doing, after my Fishing and Fishing-Plus PRs.

**Comment by StudentAlleg** [comment]
@braulio-dev @Mykindos updated original post with features that do not have it.
