### ISSUE TITLE
Create/modify system to allow for more than 6 classes at the same time

### ISSUE THREAD

**Issue by StudentAlleg** [Mykindos/BetterPvP#141]
This is explicitly not suggesting adding more than 6 classes, just a system that would make it possible and easy.

Things that would need to be done:
- [x] Define Health/Armor for class, not based on equipped armor

**Comment by StudentAlleg** [comment]
This is a low priority, more future system. It's if I run out of things to do or want to tale a break from what I am currently working on.

**Comment by Mykindos** [comment]
Closing as not expected for launch, realistically a very low demand feature
