### ISSUE TITLE
Recreate the class leaderboard rankings

### ISSUE THREAD

**Issue by ezrn** [Mykindos/BetterPvP#145]
- [x] Implement a rating system for every class so that players can see where they rank amongst others on the server
- [x] Rating should go up and down depending on kills assists and deaths
- [x] Some things that could affect rating gained/lost:
- Current Rating
- % of damage done to a kill
- % of damage done to help your teammate get a kill
- What the rating of the player you killed/died to was
- Your killstreak
- [x] Add a UI menu that will display your rank for each class, as well as the top 10 rankings for each class and a global top 10 ranking that is just the top 10 players overall in any class.
- [ ] Add rating decay feature

**Comment by braulio-dev** [comment]
We can use this sigmoid curve function as the rating win/loss per kill/death. 
![image](https://github.com/Mykindos/BetterPvP/assets/40250304/1de6e607-6508-4679-a37a-5e53d47b385a)
