### ISSUE TITLE
Double Check Colossus that KB reduction is functioning as intended

### ISSUE THREAD

**Issue by StudentAlleg** [Mykindos/BetterPvP#147]
When I pushed a quickfix to stop colossus from giving the damagee reverse KB, I just stopped it from going below a value that would deal reverse KB (lowest it can go is no KB). This implies that current implementation is not reducing by specified percent correctly. This needs to be tested, to either prove/disprove.

Issue just to make sure this is not just in my head.

**Comment by Mykindos** [comment]
This should never go to a negative value because im just multiplying by 0.25 at level 3 colossus, unless a value less between 0 and 1 is causing players to be sent in the opposite direction, but I did not see this in my tests

**Comment by Mykindos** [comment]
Fixed in https://github.com/Mykindos/BetterPvP/commit/3f1f17d89dc8c1d35aa6ded460345baeb27f2650
