### ISSUE TITLE
QOL changes for new players

### ISSUE THREAD

**Issue by ezrn** [Mykindos/BetterPvP#154]
- When hovering over the class/kit armor in any menu, it should give a description of what that kit is, its role in the game, and what it does. 
- You should be able to hover over death messages in chat that contain ability names and see what that ability does
- Hovering over armor would display both passives and the general passives as well

**Comment by Mykindos** [comment]
Agree with all, the toggleable option for weapon skills may not be possible without unnecessary lag (constantly searching peoples inventories, making sure the item lore matches for certain items, etc)

**Comment by ezrn** [comment]
then in the /skills menu you should be able to click on all your skills and see what they do

**Comment by braulio-dev** [comment]
> Agree with all, the toggleable option for weapon skills may not be possible without unnecessary lag (constantly searching peoples inventories, making sure the item lore matches for certain items, etc)

We can achieve this in a similar way to how we implemented sword blocking in the private module. Intercept outgoing item slot packets and add respective lore lines to the item meta. I don't think this could cause much overhead but we'd have to look into it

**Comment by braulio-dev** [comment]
> Agree with all, the toggleable option for weapon skills may not be possible without unnecessary lag (constantly searching peoples inventories, making sure the item lore matches for certain items, etc)

We can maybe intercept outgoing item slot packets and add respective lore lines to the item meta if they match a skill activation tool. I don't think this could cause much overhead but we'd have to look into it.
