### ISSUE TITLE
Cooldown display remains after switching classes

### ISSUE THREAD

**Issue by ezrn** [Mykindos/BetterPvP#158]
- Cooldown displays need to be wiped when swapping classes and should be completed in the background while allowing other cooldowns from another class to be displayed.

**Comment by braulio-dev** [comment]
We can add a force expiry condition [here](https://github.com/Mykindos/BetterPvP/blob/0792901357bf98f7166441e59ce3b13b0e93aa84/champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/types/CooldownSkill.java#L21)
