### ISSUE TITLE
Add recipe system to create / block recipes

### ISSUE THREAD

**Issue by Mykindos** [Mykindos/BetterPvP#160]

**Comment by StudentAlleg** [comment]
https://jd.papermc.io/paper/1.20/org/bukkit/inventory/ShapedRecipe.html seems like the best approach, along with a config for enabling the craft.

**Comment by StudentAlleg** [comment]
Current approach I am working on is using https://jd.papermc.io/paper/1.20/org/bukkit/Bukkit.html#recipeIterator() to iterate through recipes, and removing recipes that are disabled.
