### ISSUE TITLE
Create a way to track most used skills

### ISSUE THREAD

**Issue by ezrn** [Mykindos/BetterPvP#179]
- [ ] Goes through all players with >10 hours of playtime and >5 kills on the kit they are on and checks the build of their kit
- [ ] Adds each skill they have equipped to a global count
- [ ] Does this for every player in every role they meet these requirements
- [ ] Sorts Each kit individually, showing most used abilities to least used abilities
- [ ] Possibly could be added as a command to be accessed in-game

**Comment by braulio-dev** [comment]
A much better alternative for this would entail a bigger rework of how we store data. I believe Mineplex will support unstructured databases so we could just store general statistics on skills, like average flash charges used per minute or average players hit per seismic slam per player. However this would require a tremendous amount of work we just don't have the time for.

For your initial idea, we technically already have the data you're meaning to parse, which are stored builds per player. We could filter out those who haven't met the criteria.

**Comment by Mykindos** [comment]
Can be done with queries
