### ISSUE TITLE
Can hit through evade sometimes

### ISSUE THREAD

**Issue by ezrn** [Mykindos/BetterPvP#185]
https://cdn.discordapp.com/attachments/1167435289388650568/1167951531765669948/uncapped_MedalTVMinecraft20231028020218.mp4?ex=654ffea0&is=653d89a0&hm=0f85e7dfa98252e71ab19015d5d5707ee3dd7f10342a3b8f16cd262365ccc5f9&

**Comment by Mykindos** [comment]
Almost definitely related to 'soyplex' settings

**Comment by Mykindos** [comment]
Closing this until witnessed first hand
