### ISSUE TITLE
Log admin/staff actions to discord

### ISSUE THREAD

**Issue by StudentAlleg** [Mykindos/BetterPvP#195]
Along with logging to in game chat, also log to a discord webhook.

**Comment by StudentAlleg** [comment]
Waiting on whatever Kindos is doing for staff commands (i.e. structure)

**Comment by StudentAlleg** [comment]
Some notes on thoughts I've had about this. 

Why in general am I suggesting these types of changes? 
1) is that I just like information. It's useful information, you know what other staff members are doing. 
2) it helps prevent mistakes. In testing, I've run into situations where I was in a mode I didn't mean to be in, where a notification would have been helpful. Having other staff see this lets them also act as a check.
3) prevents abuse. I don't think anyone on the staff team is going to abuse, but it helps increase response time (especially for something like a compromised account). It also helps give clear logs, so that any "accusations" have more context.

Practical Thoughts
Probably have some (severity/level) system for the importance of a log (stuff like teleporting to a player isn't as important as force disbanding a Clan)

**Comment by braulio-dev** [comment]
I believe part of this has been implemented already, if I'm not mistaken. However, before this is completed, I think we should consider maybe implementing different [Appenders](https://logging.apache.org/log4j/2.x/manual/appenders.html) that relay these logs to discord, in-game chat and any other source we need in the future. 

@Mykindos and I were talking about this the other day and I think it's a great opportunity to improve the maintainability of the project by not requiring us to log to different places each time.

**Comment by StudentAlleg** [comment]
This seems to have been done via the changes to how logging works and it being stored in the database.
