### ISSUE TITLE
Right clicking iron doors activate skills

### ISSUE THREAD

**Issue by Mykindos** [Mykindos/BetterPvP#198]
When right clicking iron doors, usually the upper half it will activate your current skill. This is due to an old spigot / minecraft bug that will call a RIGHT_CLICK_AIR AND RIGHT_CLICK_BLOCK when clicking on the upper half of the door.

There are some checks in place to prevent this, it dont work though

Steps to replicate:
- Put on any sword / axe right click ability
- Place an Iron Door
- Attempt to open it a sword / axe in your hand

**Comment by StudentAlleg** [comment]
Upon doing some investigating, it looks like 2 events are being triggered. One on the door, and one after the door is opened. The first one is being blocked correctly, the second one is being processed correctly (according to the logic). 

It is acting like you are clicking on the door, and on the block behind it.
