### ISSUE TITLE
Handheld map sometimes has missing chunks

### ISSUE THREAD

**Issue by Mykindos** [Mykindos/BetterPvP#204]
Unsure on the cause, requires further investigation

Regenerating the map cache does not fix the issue

**Comment by StudentAlleg** [comment]
https://prnt.sc/M4r-gE01kTdv

Showing topography that is not currently present

**Comment by Mykindos** [comment]
> https://prnt.sc/M4r-gE01kTdv
> 
> Showing topography that is not currently present

This is because it likely got worldedited out, the actual problem on that image is this

![image](https://github.com/Mykindos/BetterPvP/assets/5389944/c27df89d-35de-4117-86ef-989e09aa2390)
