### ISSUE TITLE
Prevent creating a clan with the same name as a command

### ISSUE THREAD

**Issue by Mykindos** [Mykindos/BetterPvP#206]
i.e. /c create disband /c create ally, etc should not be permitted

**Comment by StudentAlleg** [comment]
I kinda have an inkling of how to do this. I'd also assume that we'd be using Mineplex's isChatFiltered to check Clannames in general.

**Comment by Mykindos** [comment]
> I kinda have an inkling of how to do this. I'd also assume that we'd be using Mineplex's isChatFiltered to check Clannames in general.

Yeah, wouldn't want some some gamers making edgy clan names.
It could probably be cancelled in the CreateClanEvent by using the Clans injector to get an instanceof ClanCommand, then looping through all subcommands

**Comment by Mykindos** [comment]
Fixed in https://github.com/Mykindos/BetterPvP/pull/251
