### ISSUE TITLE
/ c rename

### ISSUE THREAD

**Issue by StudentAlleg** [Mykindos/BetterPvP#207]
An admin/player command that renames the users current Clan.
Admin only implementation would be easier, don't have to worry about tracking/displaying old names as usage would be infrequent.

**Comment by Mykindos** [comment]
didnt mean to close this

**Comment by Mykindos** [comment]
Added in https://github.com/Mykindos/BetterPvP/commit/f19e4e5118897db949e1f0e5f49605388e87f708
