### ISSUE TITLE
Alligator's Tooth

### ISSUE THREAD

**Issue by braulio-dev** [Mykindos/BetterPvP#224]
- **Swim Ability:** The wielder can smooth-fly in water by holding right-click.
- While holding the item, the player has water-breathing.
- This item does high damage whilst the wielder is in water.
- Has particle cues whilst smooth-flying in water.
- Assign a randomized swim speed to each Alligator's Tooth upon item creation (event drops).

**Comment by braulio-dev** [comment]
only needs its lore done

**Comment by Mykindos** [comment]
Finished in https://github.com/Mykindos/BetterPvP/commit/c95374c0c8b6d986dcb1dde4ad68a4842b4a5a95
