### ISSUE TITLE
Energy regeneration is slowed in water

### ISSUE THREAD

**Issue by ezrn** [Mykindos/BetterPvP#258]
- Energy regenerates at a base rate which is slowed down significantly while sprinting, however this also seems to apply while being in water even if you are still in the water
- Unsure if this is an intended feature or a bug?

**Comment by StudentAlleg** [comment]
Are you moving in water? (i.e. just standing in 1 deep vs floating vs swimming)?

**Comment by ezrn** [comment]
Standing(no moving) 1 deep water

**Comment by braulio-dev** [comment]
This is intended
