### ISSUE TITLE
Channel skills don't properly activate upon switching while holding right click

### ISSUE THREAD

**Issue by ezrn** [Mykindos/BetterPvP#259]
- If you are performing a right click action(drawing bow, holding channel skill, eating food) and swap to a channel ability while holding right click it will behave unexpectedly.
- For things such as evade and riposte, it will instantly fail the ability
- Other channel abilities such as flesh hook and inferno also have unstable behavior.
- For things such as legendaries or something like battle taunt, it wont let you use them until you let go of right click and do the action again

**Comment by braulio-dev** [comment]
Fixed with #260
