### ISSUE TITLE
Make items indestructible and move durability to lore

### ISSUE THREAD

**Issue by Mykindos** [Mykindos/BetterPvP#261]
Currently we do some chance based item durability subtraction that brings all the armour pieces to around the same dura as a netherite helmet. We also do something similar for stuff like gold swords to give them a longer life span.

It will be easier if we just made them indestructible and showed the durability in the items lore instead as this is how mineplex had it. Could make use of PDC's to make lore updating cleaner.

**Comment by StudentAlleg** [comment]
This is something I can work into #256, I do agree it makes more sense to make it easier to handle/define.
