### ISSUE TITLE
Add tracking/removal of specified UIID items

### ISSUE THREAD

**Issue by StudentAlleg** [Mykindos/BetterPvP#270]
This is a stretch goal of mine that has been in the back of my head for a while.

On Mineplex, we'd sometimes track down legends that were lost to cheaters. This could be time consuming, and not always successful. Another problem was duping.

Proposal: Create a system that allows admins to specify banned UIIDs. Items with banned UIIDs, upon interaction (i.e. pickup, use) would be deleted.

This would allow admins to re-issue legends lost to cheaters, and make the fraudulently lost legends unable to be used. If a UIID item is found to be duped, that UIID could be banned, causing all instances of the dupe to be rendered useless.

**Comment by Mykindos** [comment]
This requires a bit of thought.

Ideally we don't want to be storing potentially large list of blacklisted item UUID's in memory, and then checking an item against that list whenever it is used.

I would be more inclined to store a detailed log of where said items went, when they were dropped, when they were picked up, when they were transferred from a chest, etc in a database, this way admins could just query that database to see where a specific item UUID might be at any given moment

**Comment by Mykindos** [comment]
Currently logging to a database isn't possible with the current source, It is something I had in my old code, and will be added eventually

**Comment by StudentAlleg** [comment]
I definitely like logging, any option requires accessing the database for a legend. Though could track the last known position of an UIID item through an asynchronous lookup/assignment.
