### ISSUE TITLE
Represent Durability in another way in addition to lore

### ISSUE THREAD

**Issue by StudentAlleg** [Mykindos/BetterPvP#280]
- I'd like to see if there is something we can do with the actual item durability to make it visible without needing to hover the item. Perhaps setting it to a percentage depending on the artificial durability. There may also be a way to change it without messing with the items vanilla durability at all. I don't expect you to do this as part of your PR, its something I would happily look into afterwards

_Originally posted by @Mykindos in https://github.com/Mykindos/BetterPvP/pull/256#pullrequestreview-1799523411_
            
As referenced by above, there probably should be another indicator other than lore of the current durability of the item. The two options that come to mind is 1. warn in chat at certain thresholds and 2. use the durability to represent % of item

The second option is better, but could be confusing as the damage could be confused with the custom durability.

**Comment by braulio-dev** [comment]
If we do percentile-based durability and scale the durability meter on the item then people might run into the issue of being at 2% of an item and then their item breaking because 2% for a diamond helmet won't be the same as 2% of a diamond chestplate. It'll be hard for them to know when exactly their item will break.

**Comment by StudentAlleg** [comment]
> If we do percentile-based durability and scale the durability meter on the item then people might run into the issue of being at 2% of an item and then their item breaking because 2% for a diamond helmet won't be the same as 2% of a diamond chestplate. It'll be hard for them to know when exactly their item will break.
> 
> 
> 
> I'm pretty sure this is why Mineplex didn't do this in the first place.

Durability shows the number of uses left. This is just to show durability without having to hover over item. I'm definitely leaning towards most things of the same type having the same durability (i.e. armour having the same durability), as that makes sense for our gamemmode.
