### ISSUE TITLE
Change classes to use custom health.

### ISSUE THREAD

**Issue by StudentAlleg** [Mykindos/BetterPvP#284]
Already present in #141, but since that might be a while, it would be cleaner and easier to change how damage reduction is calculated. Currently, each armour piece reduces damage by a custom percent. A better way would be to tie health to class, and reduce damage to give a class the specified ehp. Damage reduction would be done by class, not armour. Fixes mixed-armour problems, makes it clearer what health is for balance reasons.

**Comment by Mykindos** [comment]
Mixed armour was a problem on mineplex because if you didn't have a full set equipped, it would use the vanilla values instead. Because it is currently calculated per piece, mixed armour is not an issue

**Comment by braulio-dev** [comment]
Armor pieces giving individual HP points like we have now makes more sense than nullifying them until the whole set is equipped. It's a lot more intuitive and it also solves Mineplex's mixed armor issue
