### ISSUE TITLE
Dropping throwing web triggers cooldown. Cooldown does not stop throwing more webs

### ISSUE THREAD

**Issue by StudentAlleg** [Mykindos/BetterPvP#296]
Dropping throwing web triggers cooldown. Does not throw web. Cooldown does not stop throwing more webs (in general)

**Comment by braulio-dev** [comment]
Happens with any interactable action in the game. For example:
- Skills
- Energy Apples
- Fishing Baits

**Comment by StudentAlleg** [comment]
working specifically on cooldown for web, moving other to new issue

**Comment by StudentAlleg** [comment]
Cooldown is only effective when using item, not when attacking with item
