### ISSUE TITLE
Blood Compass Targets Players In Safe Zones

### ISSUE THREAD

**Issue by ezrn** [Mykindos/BetterPvP#298]
- Need to add 2 checks, one that initially checks if a player is in a safezone, and another that checks if a player is not combat tagged in a safezone but had already been targeted
- If they are in a safezone it will pass over them when checking for nearby enemies
- If they go into a safezone and are safe, the trail should reach them and make them glow, but not take damage.

**Comment by braulio-dev** [comment]
Should be fixed with with https://github.com/Mykindos/BetterPvP/commit/7933c45f1f80754a5c4c093a083c980bfaca8daa.
