### ISSUE TITLE
Badlion Client shield visuals

### ISSUE THREAD

**Issue by braulio-dev** [Mykindos/BetterPvP#319]
If a player has a shield cosmetic in Badlion Client, Badlion Client users will see that instead of the custom shield model for sword blocking.

**Comment by StudentAlleg** [comment]
might be able to do something with this
https://github.com/BadlionClient/BadlionClientModAPI

**Comment by Mykindos** [comment]
https://github.com/BadlionClient/BadlionClientModAPI/issues/41 guess we'll see

**Comment by Mykindos** [comment]
They either fix this or they dont, just wont suggest badlion as a client until a number of issues have been fixed
