### ISSUE TITLE
Cannot disable passive skills while in safezone (while active)

### ISSUE THREAD

**Issue by StudentAlleg** [Mykindos/BetterPvP#324]

**Comment by ezrn** [comment]
ezrn

**Comment by ezrn** [comment]
If you have a passive skill enabled when you walk into a safezone, it should combat tag you every tick that that ability is active, meaning you will stay permanently combat tagged(which allows you to use abilities in safe zones) until you run out of energy or toggle off the ability. This is fine IMO

**Comment by Mykindos** [comment]
personally think you should only be combat tagged if you are actively in combat

**Comment by Mykindos** [comment]
Instead of letting people toggle off, i think we can just toggle it off for them
