### ISSUE TITLE
Classes should have options for energy skills

### ISSUE THREAD

**Issue by StudentAlleg** [Mykindos/BetterPvP#329]
(balance/suggestion)
it does not really make sense that energy really only matters for mage, more classes should interact with energy

**Comment by StudentAlleg** [comment]
This means that classes need to use energy, a lot of classes have skills that can steal energy, but they don't really do anything with that energy

**Comment by StudentAlleg** [comment]
Some ideas in this strain of thing:

It takes energy to regen.
Add energy requirements to a lot of skills (i.e. on use), specifically on classes that don't use energy otherwise.

**Comment by braulio-dev** [comment]
> It takes energy to regen.
Do you mean player health regeneration? Or energy regeneration?

As a side note, I do think some - if not most - skills should use energy even if it doesn't mean that their energy will run out. Say we have three knight skills use 20% of your energy plus a cooldown, you'll never really run out of energy but you'll still be using it. It wouldn't affect the skills uptime but rather other interactions you do that use energy aside from skills, like combining Hold Position with legendaries or Throwing Webs, etc.

Definitely needs more discussion.

**Comment by StudentAlleg** [comment]
Having things like soup and webs consume energy is a good idea.

The idea being, actions you take cost energy (unless passive).

**Comment by ezrn** [comment]
This idea seems fine until you start thinkning about something like mage trying to use blizzard + an axe ability. Bascially this just makes energy intensive skills extremely bad and nobody will want to use them since if you run out of energy on one it means you cant use ANY other abilities

**Comment by Mykindos** [comment]
not overly important for now, revisit in future
