### ISSUE TITLE
Chargeable abilities like fleshhook, wolf pounce, and static lazer should not continue giving audio feedback after fully charged

### ISSUE THREAD

**Issue by StudentAlleg** [Mykindos/BetterPvP#333]

**Comment by braulio-dev** [comment]
Wolfs Pounce and other channel skills should behave like Flesh Hook and Static Lazer using the new `ChargeData` data model. This was made to avoid having a bunch of boilerplate classes.

Another thing to keep in mind for whoever takes this issue, we should probably make the default sound interval faster in `ChargeData`

**Comment by ezrn** [comment]
ill work on this
