### ISSUE TITLE
healing shot does not always proc on self if charge is too low

### ISSUE THREAD

**Issue by StudentAlleg** [Mykindos/BetterPvP#337]
this might not be fixable (or be important to fix), as the detection on self does things differently

**Comment by braulio-dev** [comment]
We can just fire a canceled damage event that can be uncanceled

**Comment by StudentAlleg** [comment]
> We can just fire a canceled damage event that can be uncanceled

it currently listens to a pre-damage event, because the event gets canceled later on in that event chain

**Comment by braulio-dev** [comment]
After some thought, arrows don't hit the shooter if the arrow hitbox hasn't left the player, which means that if you shoot the arrow with very little power and it doesn't leave your body, it won't proc like it did on Mineplex 1.8. I assume that version had a different logic, though I could be wrong. Needs further looking into.

**Comment by StudentAlleg** [comment]
> After some thought, arrows don't hit the shooter if the arrow hitbox hasn't left the player, which means that if you shoot the arrow with very little power and it doesn't leave your body, it won't proc like it did on Mineplex 1.8. I assume that version had a different logic, though I could be wrong. Needs further looking into.

That makes sense. I'm not sure how to solve this, or if it should be solved.

**Comment by ezrn** [comment]
could possibly check if the projectile has been in the shooters hitbox for more than x milliseconds and prompt the preDamageEvent off that

**Comment by Mykindos** [comment]
just check the velocity of the arrow & the direction
