### ISSUE TITLE
Smoke bomb does not re-appear while breaking blocks or swing hand

### ISSUE THREAD

**Issue by StudentAlleg** [Mykindos/BetterPvP#338]
For smokebomb, I'd kind of like to see a longer duration, but can't attack while invisible (must reappear first, maybe have a slight cooldown)

**Comment by ezrn** [comment]
ill owrk on this

**Comment by braulio-dev** [comment]
I don't think we're going to add a hit delay when coming out of smoke bomb since that's one of its main uses. We can, however, add back the restriction of not interacting with the world around you (like swinging or using skills).
