### ISSUE TITLE
Update custom items to allow cosmetic items that have the same effect as normal items.

### ISSUE THREAD

**Issue by StudentAlleg** [Mykindos/BetterPvP#353]
While it would probably be needed most for armor, but also for other items.

For armor, an "easy" solution would be to define classes based off of leggings and boots.

A better solution would be to define a BPvPItem as a range of Material+CustomModelData (as this is the current unique way to id an item).

Used for cosmetic armor (i.e. trims)

**Comment by braulio-dev** [comment]
Could you elaborate more on this issue @StudentAlleg?

**Comment by braulio-dev** [comment]
Best solution I can think of is dynamically replacing cosmetic items on outgoing packets to their respective models, so we don't have to do extra work detection item data to resolve the item type. This also allows us to implement a toggleable setting option for those who don't want to see cosmetics.
