### ISSUE TITLE
Colossus knockback issues

### ISSUE THREAD

**Issue by Armadaeiel** [Mykindos/BetterPvP#379]
- Colossus knockback reduction is way too high, negating effectively all KB at lvl 3.
- Knockback reduction applies to abilities as well (maybe an intended change, but if it's intended the knockback reduction should be heavily nerfed). This is also causing it to reduce things such as the users own Seismic Slam velocity.

**Comment by Mykindos** [comment]
Reduced to maximum of 60% (was 75%) and made it only apply to skills which are actually knockback i.e. stampede and shield smash
