### ISSUE TITLE
fix sword model on left handed people

### ISSUE THREAD

**Issue by ezrn** [Mykindos/BetterPvP#396]

**Comment by Mykindos** [comment]
which swords? example? details?

**Comment by braulio-dev** [comment]
> which swords? example? details?

1. Change your main hand to left handed in skin customization settings.
2. Hold any sword.
3. The model still has shield translations

**Comment by Mykindos** [comment]
idk what u guys were cooking but this doesnt happen to me at all

![image](https://github.com/Mykindos/BetterPvP/assets/5389944/d3b83140-8085-4ba0-8df2-20072f716cc7)
