### ISSUE TITLE
seismic slam hits players not on the ground

### ISSUE THREAD

**Issue by ezrn** [Mykindos/BetterPvP#401]

**Comment by braulio-dev** [comment]
This is intended. If we didn't hit players in the air then people could just jump as soon as slam hits the ground.

**Comment by braulio-dev** [comment]
Apparently not what @ezrn originally meant. This is the proper explanation:

![image](https://github.com/Mykindos/BetterPvP/assets/40250304/e895f816-f090-45e3-87b7-89e82161ba63)
