### ISSUE TITLE
bow durability used on hitting entity not on shooting

### ISSUE THREAD

**Issue by ezrn** [Mykindos/BetterPvP#425]
also not consumed when the arrow hits the ground

**Comment by StudentAlleg** [comment]
Durability is calculated on damage, not use.

**Comment by ezrn** [comment]
> Durability is calculated on damage, not use.

shouldnt be

**Comment by StudentAlleg** [comment]
@braulio-dev assign

**Comment by StudentAlleg** [comment]
@ezrn steps to reproduce? This behavior does not occur, however bows do take double damage when you hit an entity, which has been fixed.
