### ISSUE TITLE
Certain skills do not show the level of the skill in the chat when used/feedback about ability is given

### ISSUE THREAD

**Issue by ezrn** [Mykindos/BetterPvP#428]
- For example, a prepared arrow will tell you "You have prepared Silencing Arrow 4" where 4 is the level, but when using a skill such as wolfs pounce it will just say "You used Wolfs Pounce"

**Comment by StudentAlleg** [comment]
Instances where this is the case
- [ ] Hilt Smash Fail

**Comment by StudentAlleg** [comment]
This also seems to happen with cooldown recharge and exhaustion skills

**Comment by ezrn** [comment]
very strange, I would think it would be a fixed statement in a superclass but it seems to be on random abilities

**Comment by StudentAlleg** [comment]
Unable to fix for cooldown (recharge) and exhaustion (energy) due to how the system is setup without more work than is necessary.

**Comment by StudentAlleg** [comment]
@braulio-dev assign
