### ISSUE TITLE
You must be holding an ancient axe/golden axe for the 6th flash charge to charge

### ISSUE THREAD

**Issue by StudentAlleg** [Mykindos/BetterPvP#434]

**Comment by ezrn** [comment]
irrelevant since charge shouldnt scale with level

**Comment by Mykindos** [comment]
> irrelevant since charge shouldnt scale with level

thank you for sharing your opinion ezrn

but it is relevant because what if we want it to, either now or in the future

**Comment by ezrn** [comment]
then this brings up an interesting point, should abilities utilize a booster weapon as long as the weapon type is in their inventory even if they dont use it or should it only happen for flash? Seems impossible to check if a player is trying to use a booster axe to charge their flash or if they simply have a golden axe in their inventory and are using a diamond axe for pvp

**Comment by StudentAlleg** [comment]
> > irrelevant since charge shouldnt scale with level
> 
> thank you for sharing your opinion ezrn
> 
> but it is relevant because what if we want it to, either now or in the future

it also means that in order to get the charge rate you would have to hold the weapon

> then this brings up an interesting point, should abilities utilize a booster weapon as long as the weapon type is in their inventory even if they dont use it or should it only happen for flash? Seems impossible to check if a player is trying to use a booster axe to charge their flash or if they simply have a golden axe in their inventory and are using a diamond axe for pvp

Flash seems to be the only skill that has this problem and it is not intuitive for people.

**Comment by ezrn** [comment]
seems then like the charge system in general is problematic for booster weapons. Maybe specifically charge types should work when a booster axe is in your inventory?

**Comment by Mykindos** [comment]
not that big of a bug, can reopen later
