### ISSUE TITLE
Flash Action Bar still displays after switching classes.

### ISSUE THREAD

**Issue by StudentAlleg** [Mykindos/BetterPvP#435]
Load an Assassin build as Assassin with flash.
Change to a different kit

https://prnt.sc/gpoELj9fyR9W

**Comment by braulio-dev** [comment]
Any steps to replicate this?

**Comment by StudentAlleg** [comment]
> Any steps to replicate this?

Those were the steps, but I cannot now replicate it

**Comment by Mykindos** [comment]
How long did it stay for?

**Comment by StudentAlleg** [comment]
Until switched classes

**Comment by StudentAlleg** [comment]
On further reflection, this might have been me mistaking level field display for flash. I don't remember what knight build I was running
