### ISSUE TITLE
If player does not release after using shield smash, the shield remains

### ISSUE THREAD

**Issue by StudentAlleg** [Mykindos/BetterPvP#438]
Unknown if this changes gameplay, or if this is client only. Needs testing with multiple players.

**Comment by braulio-dev** [comment]
I left this on purpose

**Comment by ezrn** [comment]
you meant for the shield to stay permanently not just when the ability was cast?

**Comment by braulio-dev** [comment]
> you meant for the shield to stay permanently not just when the ability was cast?

it doesn't stay permanently. it only stays for as long as you hold your right click. if you hold your click on shield smash you'll have that shield until you unclick

**Comment by Mykindos** [comment]
I kinda liked having the shield always present as long as you had an equipped, its like an indicator that people are using the skill

**Comment by StudentAlleg** [comment]
> I kinda liked having the shield always present as long as you had an equipped, its like an indicator that people are using the skill

I think this is a good reason to have it always, more skills need this type of thing
