### ISSUE TITLE
feedback when using an ability while silenced

### ISSUE THREAD

**Issue by ezrn** [Mykindos/BetterPvP#461]
- Instead of saying "You cannot use X while silenced" it should say "You are silenced for X more seconds"
- This is overall a more helpful line of feedback

**Comment by braulio-dev** [comment]
I feel we could rename and retexture some useless potion effect to be 'silencing' and keep this message, then people's clients will pick up how long the effect has remaining on their effect hud or in their inventory

**Comment by ezrn** [comment]
Yeah that would probobly be a good idea actually
