### ISSUE TITLE
add the clans bed c home

### ISSUE THREAD

**Issue by ezrn** [Mykindos/BetterPvP#472]

**Comment by Mykindos** [comment]
Not sure i want it but could be convinced

**Comment by ezrn** [comment]
> Not sure i want it but could be convinced

It serves both as a visual for enemies and clanmates to show where the clan will spawn when they c home, and it also serves to add counterplay once you get inside someones base by being able to break their bed. It makes it important to put your clan home in a protected spot so that players can't break it.

**Comment by Mykindos** [comment]
yeah but why a bed, shit takes up 2 blocks and looks bad

**Comment by ezrn** [comment]
> yeah but why a bed, shit takes up 2 blocks and looks bad

absolutely doesnt have to be a bed but its a good symbol for a clan "home". If theres a better block it could definitely be used instead
