### ISSUE TITLE
evade invisibility 

### ISSUE THREAD

**Issue by ezrn** [Mykindos/BetterPvP#503]
before evade was able to be spammed, it had an old functionality where the player using it would dissapear for a tick or two while teleporting. This was especially useful for backwards evading and also made evade overall a more powerful tool for getting in hits. If the route of spamming evade is not desired then this could be considered to keep the ability good while not making it spammable. not sure if this is a good idea since there was probobly a reason it was removed but interesting thought since backwards evading is pretty useless atm

**Comment by StudentAlleg** [comment]
Brief durations of invisibility is rough. This also had a side effect of giving invincibility while invisible, which might still be a thing with smoke bomb used in a similar manner.

**Comment by RealSoy** [comment]
ADD EVADE SPAM INSTEAD!!!!
