### ISSUE TITLE
add indicator to build menu that shows amount increase on the next upgrade

### ISSUE THREAD

**Issue by ezrn** [Mykindos/BetterPvP#505]
- mineplex had this and it was rather nice

**Comment by StudentAlleg** [comment]
"<val> + getAttribute(level) + "</val> + <val>" + getAttribute(level + 1) - getAttribute(level) + "</val>"

**Comment by ezrn** [comment]
would prefer it as a simple function in that I could type in tyhe desc, much like mineplex used x#y for it

**Comment by Mykindos** [comment]
low priority, not expected for launch

**Comment by Mykindos** [comment]
Just clearing out the issues for ones we only want to consider for launch
