### ISSUE TITLE
say skill level next to skill name in actionbar

### ISSUE THREAD

**Issue by ezrn** [Mykindos/BetterPvP#551]

**Comment by Mykindos** [comment]
honestly dont think this is necessary

**Comment by ezrn** [comment]
simply a qol thing, allows the user to see their ability level on the actionbar instead of having to check their ./skill to see. Obvioulsly super niche but also a very easy change to implement

**Comment by Mykindos** [comment]
looks bad and is annoying to implement, wont do for now
