### ISSUE TITLE
Implement some sort of trading system/auction house/black market where playres can trade items for other items or for money

### ISSUE THREAD

**Issue by ezrn** [Mykindos/BetterPvP#556]
- This would be a safe way to trade things like legendaries
- Would allow people less inclined to pvp access to things such as event tokens

- Possible considerations would be to prevent people from using this to warpoint evade/gear evade
- Could even be linked to the clan vault in some way

**Comment by Mykindos** [comment]
There is already a ticket for auction housing, it wont be for season 1
