### ISSUE TITLE
make legendaries use custommodeldata so that music discs are visible by default

### ISSUE THREAD

**Issue by ezrn** [Mykindos/BetterPvP#599]
Currently they use the 0 slot, they should use a different custommodeldata slot so that discs are visible by default

**Comment by StudentAlleg** [comment]
Already answered in discord, but legends do use custom model data.

Should be rephrased, custom model data slot 0 should show music disk, custom model data slot 1 should show the legend.

**Comment by ezrn** [comment]
> Already answered in discord, but legends do use custom model data.
> 
> Should be rephrased, custom model data slot 0 should show music disk, custom model data slot 1 should show the legend.

if you read the bullet point I wrote in the issue description you would see that I already gave that information

**Comment by Mykindos** [comment]
done
