### ISSUE TITLE
Legends do not show UUID in lore

### ISSUE THREAD

**Issue by StudentAlleg** [Mykindos/BetterPvP#601]

**Comment by Mykindos** [comment]
I did this intentionally, users dont need to know that info if we have automated checks

**Comment by StudentAlleg** [comment]
> I did this intentionally, users dont need to know that info if we have automated checks

But it does mean that say you lost a legend, it's more difficult to prove which one. Also, it helps people keep track of their legends.

**Comment by ezrn** [comment]
> > I did this intentionally, users dont need to know that info if we have automated checks
> 
> But it does mean that say you lost a legend, it's more difficult to prove which one. Also, it helps people keep track of their legends.

why would you ever need to prove that you lost a legend, if you were using a legendary and it was lost due to a bug/hacker can it not just be given back regardless of UUID?

**Comment by Mykindos** [comment]
> > > I did this intentionally, users dont need to know that info if we have automated checks
> > 
> > 
> > But it does mean that say you lost a legend, it's more difficult to prove which one. Also, it helps people keep track of their legends.
> 
> why would you ever need to prove that you lost a legend, if you were using a legendary and it was lost due to a bug/hacker can it not just be given back regardless of UUID?

because the hacker could have just given it to a friend, so instead of introducing another legendary to the economy, its better to just give the original back

**Comment by StudentAlleg** [comment]
In theory we could look it up and determine it, but it is a lot easier not to do that.
