### ISSUE TITLE
hitting through fencegates

### ISSUE THREAD

**Issue by moorings** [Mykindos/BetterPvP#615]
not sure if this is known or not but you can hit through open fencegates as long as they are within reach of you; you dont even have to be up against it to do it [https://medal.tv/games/minecraft/clips/1WmYGaVhGPJEkw/d1337q6dYGTV?invite=cr-MSxJZHYsNDkyNDEwNTgs](url)

**Comment by Mykindos** [comment]
@braulio-dev is this ur hitbox stuff or vanilla behaviour

**Comment by moorings** [comment]
> @braulio-dev is this ur hitbox stuff or vanilla behaviour

i would think it would be vanilla behavior because i could still hit them even though they were not up against the fence gate

**Comment by Mykindos** [comment]
> > @braulio-dev is this ur hitbox stuff or vanilla behaviour
> 
> i would think it would be vanilla behavior because i could still hit them even though they were not up against the fence gate

its from the ray trace on the expanded hitbox, confirmed by testing on a villager with and without hitbox size increase

**Comment by Mykindos** [comment]
Honestly not sure if we should fix this, you can hit through open doors, why shouldnt you be able to hit through open fence gates

thoughts @braulio-dev ?

**Comment by RealSoy** [comment]
people r gonna be confused on how people r hitting them through their fence gate doors

**Comment by Mykindos** [comment]
theyl be confused once and then realise you can hit through open fence gates

**Comment by ezrn** [comment]
arguing against this is literally the definition of being allergic to change

**Comment by RealSoy** [comment]
ezrn with the L opinions once again

**Comment by Mykindos** [comment]
i like this
