### ISSUE TITLE
Add runed pickaxe

### ISSUE THREAD

**Issue by ezrn** [Mykindos/BetterPvP#623]
- Default mining speed of netherite pickaxe
- Could add a cooldown based or even energy based ability that allows the user to instantly mine stone-type blocks
- Should only be usable on stone-type blocks
- Same rarity as an epic/legendary imbuement

**Comment by Polisvh** [comment]
My god just make it how it was on mineplex, why you wanna make it only work in claim. You ezrn rly sometimes have bad as hell ideas

Tf you need energy for runed pickaxe? Just give it q cooldown as its always been.

**Comment by RealSoy** [comment]
ong runed pickaxe gotta be like the least problematic weapon ever

**Comment by StudentAlleg** [comment]
^ Incorrect issue, does not relate to this

**Comment by braulio-dev** [comment]
I don't think this need to be nerfed at all if we're moving from cobblestone to farming-based economy. If anything this will make the legendary a lot more situational and useless more often than not.

**Comment by ezrn** [comment]
> I don't think this need to be nerfed at all if we're moving from cobblestone to farming-based economy. If anything this will make the legendary a lot more situational and useless more often than not.
> 
> Up to @Mykindos though

Depends what the intended purpose for the ruined pick is. It was only ever used for cobble farming and base clearing on mineplex, so could possibly give it some extra use since cobble mining isn't as profitable anymore
