### ISSUE TITLE
Sword goes "down" when upgrading skills in the skill menu

### ISSUE THREAD

**Issue by ezrn** [Mykindos/BetterPvP#650]

**Comment by Mykindos** [comment]
the quotations dont help here, i still have no idea

**Comment by ezrn** [comment]
Didn't realize it was unclear. It is as if your sword was replaced with a new one in your inventory(which is probably what is happening, at least the data of the sword is being modified), the sword goes down slightly in your hand when performing certain things. You can recreate by opening an enchantment table and upgrade and downgrading skills, or block you block with a sword.

**Comment by Mykindos** [comment]
This is the change student made the other day where it puts your current skill on the tooltip of the weapon. Lore changes seem to trigger this effect, its why you also see it when the durability is updated
