### ISSUE TITLE
Add some sort of effect index or way for players to see the qualities of all the custom effects

### ISSUE THREAD

**Issue by ezrn** [Mykindos/BetterPvP#651]

**Comment by StudentAlleg** [comment]
This is something I have been mulling over. We definitely need something like this for the non-normal Clans related things.

**Comment by Mykindos** [comment]
im going to include it in skill tooltips at the bottom, so if a skill applies vulnerability it will attach the vulnerability description on the bottom of the tooltip

**Comment by ezrn** [comment]
thats a good idea
