### ISSUE TITLE
Wolfs fury bugs

### ISSUE THREAD

**Issue by ezrn** [Mykindos/BetterPvP#652]
- Wolfs fury needs to fail if the player swaps off their axe
- Missed swings per level is increasing by 0.5 per level when its supposed to be 1

**Comment by Mykindos** [comment]
The missed swings increasing by 0.5 is intentional, it didn't exist at all on mineplex. This way you only get 1 extra swing if you assign 2 points to the skill

**Comment by ezrn** [comment]
if it didnt exist on mineplex why is it being added in the first place? the high strength level with the hard skill requirement made the skill fun

**Comment by Mykindos** [comment]
> if it didnt exist on mineplex why is it being added in the first place? the high strength level with the hard skill requirement made the skill fun

because strength on mineplex was 1.0 damage per level, and on here its 1.5
I essentially brought it down from the 4 bonus damage it was on mineplex to 3, and in exchange for the small nerf I made it scale in another area as well

**Comment by ezrn** [comment]
> > if it didnt exist on mineplex why is it being added in the first place? the high strength level with the hard skill requirement made the skill fun
> 
> because strength on mineplex was 1.0 damage per level, and on here its 1.5 I essentially brought it down from the 4 bonus damage it was on mineplex to 3, and in exchange for the small nerf I made it scale in another area as well

ah that makes sense didn't realize strength scaled differently
