### ISSUE TITLE
Dropping the Scepter to trigger drop abilities fires the beam

### ISSUE THREAD

**Issue by StudentAlleg** [Mykindos/BetterPvP#656]
While aiming at air (not block/player), drop the scepter while using a drop toggled skill.
Both the skill and the beam will be triggered.

**Comment by ezrn** [comment]
probobly would have the same issue with glacial blade, ex any left click activation for a skill since activating a drop ability swings your weapon

**Comment by Mykindos** [comment]
There is a fix in the code for this, it likely just wasnt applied to either glacial / scepter
