### ISSUE TITLE
Campfire Idea

### ISSUE THREAD

**Issue by ezrn** [Mykindos/BetterPvP#659]
- make campfires a somewhat expensive shop item and make them give regen to players within a certain radius

**Comment by braulio-dev** [comment]
What would the use of this be? Only to put in your base to reduce fight downtime after moating or escaping into your base?

**Comment by ezrn** [comment]
That, also could bring them to events and stuff(allow them peaceable in a claim with an expiry timer or something)

**Comment by Mykindos** [comment]
maybe later
