### ISSUE TITLE
Poor Takedown collision detection, less intended damage, doesn't stop momentum on collision

### ISSUE THREAD

**Issue by ezrn** [Mykindos/BetterPvP#665]
also doing 1 less damage than intended
also needs to stop their momentum when they hit a target

**Comment by braulio-dev** [comment]
If anybody wants to take this, for the collision detection you could take a peek at how we check for collisions in the [Knight's Greatlance](https://github.com/Mykindos/BetterPvP/blob/master/champions/src/main/java/me/mykindos/betterpvp/champions/weapons/impl/legendaries/KnightsGreatlance.java) with [interpolateCollision](https://github.com/Mykindos/BetterPvP/blob/7bb2aba787d57a366b480aa467fd7055db7dd352/core/src/main/java/me/mykindos/betterpvp/core/utilities/UtilEntity.java#L96-L109) utility method.
