### ISSUE TITLE
New Global Passive - Gluttony

### ISSUE THREAD

**Issue by RockyMichael** [Mykindos/BetterPvP#666]
Gluttony would be a Global Passive that would allow for you to use Soups at a faster rate by decreasing the global cooldown. 

Level 1 would be 2 seconds off of the cooldown, Level 2 would be 4 seconds, and Level 3 would be 6 seconds.

**Comment by braulio-dev** [comment]
I feel this would be too overpowered since it gives soups an almost 100% uptime (under the assumption that the duration is 4.0 and the cooldown is 6.0)

**Comment by RockyMichael** [comment]
I think it was misinterpreted on the original values. The default cooldown is 14 seconds so at Level 3 I proposed a 6 second reduction in the cooldown so the total cooldown would be 8 seconds.

However the numbers can always be tweaked. Perhaps the scaling should be more in the lines of 1.5 seconds per level? So 12.5 total cooldown for Level 1, 11 for Level 2, and 9.5 For Level 3? 

I personally like this idea because right now soups feel underwhelming so being able to sacrifice a skill token or two for more soup value could be interesting, in my opinion.

**Comment by ezrn** [comment]
Also its a passive skill, so if someone wants to put an entire 3 skill tokens into a global passive then I feel like its fair to have very high soup uptime

**Comment by StudentAlleg** [comment]
> I feel this would be too overpowered since it gives soups an almost 100% uptime (under the assumption that the duration is 4.0 and the cooldown is 6.0)

I don't feel like soup uptime is even a huge issue, this isn't instant health, you can only heal so fast.

**Comment by braulio-dev** [comment]
I wouldn't want a passive that relies on you having any items in your inventory to work. It makes it effectively useless if you don't have soups
