### ISSUE TITLE
some legends issues as rey asked

### ISSUE THREAD

**Issue by Polisvh** [Mykindos/BetterPvP#672]
- Scythe heals by attack sent packet not by actually dealing damage which makes it way better
- Idk MAYBE lance is faster than it used to but Maybe it's just me

https://youtu.be/pQ3BndBBu-Q

**Comment by Mykindos** [comment]
- Windblade deals 3.5 damage
- Hyper axe does not reduce hit delay
- broadsword gives Regeneration 3 effect for eternity

fixed these so removed them from the description

**Comment by Mykindos** [comment]
fixed all but lance, believe there is another issue for that
