### ISSUE TITLE
Implement Trident and Mace

### ISSUE THREAD

**Issue by ezrn** [Mykindos/BetterPvP#676]
- Add the Trident and the Mace when it releases as a rare-type item like the ruined pickaxe
- Could be the same rarity as an Epic rune, and would spice up general combat more commonly than a legendary, while being less powerful
- Trident would need the enchantment that makes it recall back to you, and Mace would need some small vertical mobility ability to properly utilize its falling damage amplification

**Comment by braulio-dev** [comment]
save this for season 17

**Comment by ezrn** [comment]
> save this for season 17

if I'm still working on clans in season 17 I will end it all
