### ISSUE TITLE
QOL UI renovations

### ISSUE THREAD

**Issue by braulio-dev** [Mykindos/BetterPvP#68]
There's a bunch of command-based features that could very well be implemented in a more user-friendly and visually appealing way through GUIs.

- [ ] Anything from the `/c` command @ezrn 
- [ ] Champions skill/kit/build editor
- [ ] Leaderboard GUI
- [ ] (Possibly) Stats GUI

Finally, all GUIs need to be consistent across the whole board, meaning we need to homogenize display messages, title coloring, etc.

**Comment by StudentAlleg** [comment]
This needs to be done, but I'm concerned that we will just have to re-implement. https://studio.mineplex.com/docs/sdk/gui
