### ISSUE TITLE
Allow admins to claim territory over limit.

### ISSUE THREAD

**Issue by StudentAlleg** [Mykindos/BetterPvP#71]
Allow admins in /client admin to claim more than the allowed claims. Add something to prevent overclaiming territory for Clans that are over the territory limit but have an admin in client admin (probably something that checks members to see if they are in client admin).

This is based on a specific time where something went wrong (I don't remember what, it was probably my fault) so I had to reform a Clan. There was not enough players from that Clan online, so even though I could claim past the limit, other players would come over and unclaim territory.

Combination of these two things would help fixing mistakes.

**Comment by Mykindos** [comment]
They can already do this, unless you mean for a clan that wasn't created while in /client admin

**Comment by StudentAlleg** [comment]
It would need to be for non-admin clans too (in case of an accidental/mistaken disband)
