### ISSUE TITLE
Switching to Flash or Recall from a build that does not have that skill makes that skill unusable

### ISSUE THREAD

**Issue by StudentAlleg** [Mykindos/BetterPvP#748]
Steps to reproduce:

1. Be Assassin.
2. Equip a build that does not have flash and/or recall
3. Switch to a build that has flash and/or recall
4. Flash and/or recall will not be usable

Re-equipping, dying, or re-logging fixes the affected skill(s), allowing them to be used again.

Discovered with @manu10000

**Comment by manu10000** [comment]
Pretty sure it only happens when either the blink/leap/smokebomb cooldowns are activated

E.g.

You blink -->
Switch build to flash
Flash does not charge up.
