### ISSUE TITLE
Shop issues

### ISSUE THREAD

**Issue by StudentAlleg** [Mykindos/BetterPvP#768]
Gravity Bomb, Purifying Capsule, EMP Grenade, and Incendiary grenade all return the base item (not the custom item). (This seems intentional since these items are not in the code.

Clicking sell 64 sells the first stack in the inventory, which may not be 64 (even if you have more than 64 total in your inventory)

**Comment by Mykindos** [comment]
selling is intentional, i removed the other items from store
