### ISSUE TITLE
Invsee

### ISSUE THREAD

**Issue by StudentAlleg** [Mykindos/BetterPvP#77]
Add the ability for Admins to see/modify the inventories of players.

**Comment by StudentAlleg** [comment]
Specifically waiting on Mineplex Studio to even attempt this.

**Comment by Mykindos** [comment]
https://github.com/Mykindos/BetterPvP-Core/blob/master/src/main/java/net/betterpvp/core/client/commands/OpenInvCommand.java

Could just copy this, no need to wait for mineplex studio
