### ISSUE TITLE
Players are able to use abilities for short times popping out of the water.

### ISSUE THREAD

**Issue by StudentAlleg** [Mykindos/BetterPvP#78]
While holding space and being on the surface of the water, the player will pop up and not register as being in water, allowing for abilities to be used for a brief period of time.

**Comment by StudentAlleg** [comment]
I have an idea of how to fix this, which would be to track the last time the player was in water, then if they are out of water but it has been less than time act like you are still in water.

**Comment by Mykindos** [comment]
You could probably just check if the block 0.1y below a player is water

**Comment by StudentAlleg** [comment]
probably would be better

**Comment by ezrn** [comment]
dont see why promoting moats is a good idea

**Comment by StudentAlleg** [comment]
Partially solved, framework is in code for future tweaks.
