### ISSUE TITLE
You cannot break other Clans c homes

### ISSUE THREAD

**Issue by StudentAlleg** [Mykindos/BetterPvP#802]
because adventure

**Comment by Mykindos** [comment]
Pretty sure we can fix this in a nice way in 1.20.6

**Comment by braulio-dev** [comment]
Clan home behavior is changed with https://github.com/Mykindos/BetterPvP/pull/962. A clan must have a home/core at all times so it won't be able to be broken by anyone, not even the owning clan itself.
