### ISSUE TITLE
Prevent switching kits in combat

### ISSUE THREAD

**Issue by StudentAlleg** [Mykindos/BetterPvP#818]

**Comment by StudentAlleg** [comment]
I looked into this, there isn't an easy cancellable event, so will have to do the magic with inventory events. It might be worth creating custom events, so we don't have to do this magic every time.
Not high priority for finish during kitmap.

**Comment by manu10000** [comment]
I think how nekoliplex did it was a decent way

Just make it so you can't mix armour sets that way clicking your hotbar will be useless as you have to take off the full set before applying the other set

**Comment by Mykindos** [comment]
This was done a couple of days ago
