### ISSUE TITLE
Evade can go through impassable blocks in some situations

### ISSUE THREAD

**Issue by StudentAlleg** [Mykindos/BetterPvP#857]
https://discord.com/channels/161738857136521217/1248774138362073159/1248774138362073159

**Comment by StudentAlleg** [comment]
https://discord.com/channels/161738857136521217/1247708839017447443

**Comment by ezrn** [comment]
I think that this would also be a good time to address the inconsistent evade locations when using the ability and the shift evade functionality. Nobody uses shift evade and it should be removed, also evade doesn't always put you the same distance behind your opponent, sometimes it will put you inside of them depending on how far away you were when you evaded which seems weird to me.
