### ISSUE TITLE
All skills should give feedback when hit by them

### ISSUE THREAD

**Issue by StudentAlleg** [Mykindos/BetterPvP#881]
- [ ] Whirlwind Sword
- [ ] Sever
- [ ] Defensive Aura
https://discord.com/channels/161738857136521217/1246651271570788392

**Comment by ezrn** [comment]
and the user should get feedback when they hit an ability: example slash

**Comment by Mykindos** [comment]
Sever also tells you, and gives you a potion effect labelled 'Bleed'

https://github.com/Mykindos/BetterPvP/blob/82b0db98e4e706afb8cd3a4d35c70fe4a4d36529/champions/src/main/java/me/mykindos/betterpvp/champions/champions/skills/skills/assassin/sword/Sever.java#L126
