### ISSUE TITLE
Make all damage for champions be in effective health

### ISSUE THREAD

**Issue by StudentAlleg** [Mykindos/BetterPvP#907]
This was already done with fall damage, but should be done for things like bleed, poison, regeneration (be affected by damage reduction). Health/damage should default to being ehp (this is a thing for damage, somewhat for health). I.e. Regeneration heals 1 health /s (meaning 1 ehp/s). If want it to be true health, change to regeneration heals 10% base health / second.

Defining in terms of one system reduces confusion. The damage reduction is already confusing, everything should be defined in terms of the same base.

**Comment by Mykindos** [comment]
Disagree, its like this in vanilla minecraft as well

Some things are reduced by armour, some things are not e.g. falling, drowning, and magic type attacks

**Comment by StudentAlleg** [comment]
> Disagree, its like this in vanilla minecraft as well
> 
> Some things are reduced by armour, some things are not e.g. falling, drowning, and magic type attacks

Yes, but it's not clear here which one instance it is. Because some things are changed from vanilla and having to learn whether does 1 damage a second means 1 true damage a second/1 effective health a second, or something does 7 true damage or 7 effective damage is a higher cognitive balance. Defining in terms of effective is closer to the effect people are expecting, meaning they don't have to do armor conversions/other things, this has already been done for them.

**Comment by braulio-dev** [comment]
I'm more confused trying to understand it in effective health than assimilating it with vanilla behaviors like Kindos said. I don't think we should do this either.
