### ISSUE TITLE
make it so flash doesnt change ur pitch and yaw

### ISSUE THREAD

**Issue by RealSoy** [Mykindos/BetterPvP#947]
i think this would make flashing on higher ping way easier and enjoyable since you can instantly rotate ur head after flashing, instead of waiting for the flash to go through then rotating your head

**Comment by manu10000** [comment]
sounds broken tbh, don't want people pre aiming between that delay flash

**Comment by manu10000** [comment]
> YOU PLAY ON HIGH PING TRUST ME IT FEELS SO GOOD WITHOUT IT

hmm yeah, maybe it is a good thing

**Comment by braulio-dev** [comment]
Flash already doesn't change your pitch and direction. The only way this could happen is if you flash, you lag before you are teleported, and then you are teleported.

![image](https://github.com/user-attachments/assets/bbd3dffb-dcab-43e8-80e2-ed14280efd67)

**Comment by manu-y** [comment]
> > Flash already doesn't change your pitch and direction. The only way this could happen is if you flash, you lag before you are teleported, and then you are teleported.
> > ![image](https://private-user-images.githubusercontent.com/40250304/351138435-bbd3dffb-dcab-43e8-80e2-ed14280efd67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MTMxNzAsIm5iZiI6MTcyMTcxMjg3MCwicGF0aCI6Ii80MDI1MDMwNC8zNTExMzg0MzUtYmJkM2RmZmItZGNhYi00M2U4LTgwZTItZWQxNDI4MGVmZDY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDA1MzQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4MjMyOTczOTE3ZTRhOTE4OTNkOWRmMGEyZmE5ZjhhOTAzY2NlMDc0ZTU0M2MxMzBmN2FkODM5NjU0YWNkN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3yVtTeJHTTGl1F1RqGtWS4F_dFq0JyLGL2DmFBu1xlo)
> 
> is there a reason it sets your pitch and yaw? it makes flash harder to use for me imo

Teleporting requires a pitch and yaw value iirc
