### ISSUE TITLE
Global Passive Updates

### ISSUE THREAD

**Issue by RockyMichael** [Mykindos/BetterPvP#977]
Buff Resistance - Change Level Scaling from 20/30/40% to 40/60/80% 
Buff Break Fall - Change Level Scaling from 2/4/6 to 5/10/15 Blocks

Remove Fast Recovery - Add Tranquility
Tranquility:
When Out of Combat for 9/7/5 Seconds, gain Regeneration 1

**Comment by manu-y** [comment]
whole concept of global passives is useless, no one actually uses them...

**Comment by RockyMichael** [comment]
thats why im proposing to give them buffs

**Comment by 8SIXSect** [comment]
I like the changes but I think fast recovery still has a place in the game

**Comment by RockyMichael** [comment]
Fast recovery has proven to be problematic for clans leading to legend spam and certain ability spam, it'd be best replaced with something else

**Comment by Mykindos** [comment]
we wont be removing fast recovery, we already nerfed its rate from the alpha significantly

**Comment by Mykindos** [comment]
From a balance perspective this is slightly dumb, that is an INSANE buff to break fall, perhaps 4 / 8 / 12 is a better start

**Comment by RockyMichael** [comment]
Okay how about 4/8/12 for Break Fall and adding Tranquility as a separate, 4th Global Passive
